export const SITE_IMAGE_REGISTRY = [
  {
    setting_key: "site_logo_url",
    section: "Branding",
    label: "Site Logo",
    description: "Primary logo used in the header and footer.",
    recommended_size: "400x120px",
    folder: "branding",
  },
  {
    setting_key: "hero_bg_image",
    section: "Homepage",
    label: "Hero Background",
    description: "Large background image for the homepage hero section.",
    recommended_size: "1920x1080px",
    folder: "homepage",
  },
  {
    setting_key: "cause_bg_image",
    section: "Homepage",
    label: "Campaign Section Background",
    description: "Background image behind the campaign section.",
    recommended_size: "1920x1080px",
    folder: "homepage",
  },
  {
    setting_key: "community_bg_image",
    section: "Homepage",
    label: "Community Section Background",
    description: "Background image for the community section.",
    recommended_size: "1920x1080px",
    folder: "homepage",
  },
  {
    setting_key: "impact_image_url",
    section: "Homepage",
    label: "Impact Section Image",
    description: "Main image shown in the impact/story section.",
    recommended_size: "900x1100px",
    folder: "homepage",
  },
  {
    setting_key: "testimonial_avatar_url",
    section: "Homepage",
    label: "Testimonial Avatar",
    description: "Avatar image used for the featured testimonial.",
    recommended_size: "300x300px",
    folder: "homepage",
  },
  {
    setting_key: "partner_logo_1",
    section: "Partners",
    label: "Partner Logo 1",
    description: "First partner logo shown on the homepage.",
    recommended_size: "240x120px",
    folder: "partners",
  },
  {
    setting_key: "partner_logo_2",
    section: "Partners",
    label: "Partner Logo 2",
    description: "Second partner logo shown on the homepage.",
    recommended_size: "240x120px",
    folder: "partners",
  },
  {
    setting_key: "partner_logo_3",
    section: "Partners",
    label: "Partner Logo 3",
    description: "Third partner logo shown on the homepage.",
    recommended_size: "240x120px",
    folder: "partners",
  },
  {
    setting_key: "partner_logo_4",
    section: "Partners",
    label: "Partner Logo 4",
    description: "Fourth partner logo shown on the homepage.",
    recommended_size: "240x120px",
    folder: "partners",
  },
  {
    setting_key: "partner_logo_5",
    section: "Partners",
    label: "Partner Logo 5",
    description: "Fifth partner logo shown on the homepage.",
    recommended_size: "240x120px",
    folder: "partners",
  },
];

export function looksLikeImageUrl(value = "") {
  return typeof value === "string" && /^(https?:\/\/|\/)/.test(value);
}
