const repeat = (count, factory) => Array.from({ length: count }, (_, index) => factory(index + 1)).flat();

export const DEFAULT_SITE_SETTINGS = {
  site_name: 'IRWA',
  site_logo_url: '',
  contact_email: 'info@irwa.org',
  contact_phone: '(+01)-793-7938',
  contact_address: '123 Charity Lane, NY 10001',
  social_facebook: 'https://www.facebook.com/',
  social_twitter: 'https://x.com/',
  social_instagram: 'https://www.instagram.com/',
  social_linkedin: 'https://www.linkedin.com/',
  footer_description: 'Sharing beneficial knowledge, trusted guidance, and meaningful causes that serve the community.',
  hero_bg_image: '',
  cause_bg_image: '',
  community_bg_image: '',
  hero_subtitle: 'Dawah, Guidance, and Giving',
  hero_title: 'Knowledge That Guides, Causes That Matter',
  hero_description: 'Build a stronger Muslim community through beneficial articles, trusted fatwas, and causes that turn faith into action.',
  hero_primary_cta_text: 'Explore Fatwas',
  hero_primary_cta_link: '/fatwa',
  hero_secondary_cta_text: 'Read Articles',
  hero_secondary_cta_link: '/blog-grid',
  hero_support_cta_text: 'Support our causes',
  hero_support_cta_link: '/#campaigns',
  hero_stat_1_value: 'New',
  hero_stat_1_label: 'Fatwas & Guidance',
  hero_stat_2_value: 'Weekly',
  hero_stat_2_label: 'Articles & Reminders',
  hero_stat_3_value: 'Active',
  hero_stat_3_label: 'Community Causes',
  hero_card_1_title: 'Articles',
  hero_card_1_meta: 'Reflections & learning',
  hero_card_2_title: 'Fatwas',
  hero_card_2_meta: 'Trusted answers',
  hero_card_3_title: 'Dawah',
  hero_card_3_meta: 'Community benefit',
  hero_card_4_title: 'Causes',
  hero_card_4_meta: 'Support in action',
  campaign_section_badge: 'Active Campaigns',
  campaign_section_title: 'Help & donate to make a difference',
  campaign_section_description: 'Support campaigns that extend care, strengthen families, and serve the wider mission with lasting impact.',
  campaign_section_empty_title: 'No Campaigns Yet',
  campaign_section_empty_description: 'Check back soon for new fundraising campaigns!',
  campaign_discovery_badge: 'Causes That Support the Mission',
  campaign_discovery_title: 'Support Our Causes',
  campaign_discovery_description: 'Give to projects that extend care, strengthen the community, and support the wider work of dawah.',
  fatwa_highlights_badge: 'Featured Fatwas',
  fatwa_highlights_title: 'Guidance That Answers Real Questions',
  fatwa_highlights_description: 'Highlighting fatwas near the top helps the site feel trusted, useful, and rooted in beneficial knowledge from the first scroll.',
  fatwa_highlights_cta_text: 'View All Fatwas',
  blog_badge_text: 'Islamic Insights',
  blog_title: 'Islamic Insights',
  blog_subtitle: 'Explore reflections, reminders, and practical articles that strengthen faith and deepen understanding.',
  blog_tag_1: 'Dawah',
  blog_tag_2: 'Tazkiyah',
  blog_tag_3: 'Community',
  blog_tag_4: 'Guidance',
  blog_browse_cta_text: 'Browse All Articles',
  impact_badge: 'Make A Difference',
  impact_title: 'Every Act of Kindness Creates a Ripple Effect',
  impact_description: 'We believe that no contribution is too small. Together, our collective efforts are building schools, providing clean water, and responding to medical emergencies across the globe.',
  impact_image_url: '',
  impact_image_alt: 'Impact Image',
  impact_stat_value: '15+',
  impact_stat_label: 'Years of Global Impact',
  impact_point_1: 'Transparent donation tracking from start to finish',
  impact_point_2: 'Direct partnership with local organizations',
  impact_point_3: 'Tax-deductible contributions globally',
  impact_cta_text: 'Discover Our Story',
  impact_cta_link: '/about-us',
  journey_badge: 'How It Works',
  journey_title: 'Your Journey of Giving',
  journey_description: 'A simple, transparent process ensures your donation makes the maximum possible impact.',
  journey_step_1_title: 'Choose a Cause',
  journey_step_1_description: 'Browse our verified campaigns and find a mission that speaks to your heart.',
  journey_step_2_title: 'Make a Donation',
  journey_step_2_description: 'Contribute safely and securely using our Stripe-powered payment system.',
  journey_step_3_title: 'Track the Impact',
  journey_step_3_description: 'Receive updates as the campaign reaches its goals and changes lives.',
  help_badge: 'Get Involved',
  help_title: 'How You Can Help',
  help_description: 'There are many ways to support our mission. Whether it is your time, voice, or resources, we need you.',
  help_card_1_title: 'Make a Donation',
  help_card_1_description: 'Provide financial support to fund our global initiatives and immediate relief efforts.',
  help_card_1_button_text: 'Donate',
  help_card_1_link: '/donation',
  help_card_2_title: 'Become a Volunteer',
  help_card_2_description: 'Join our team on the ground or help us remotely with your skills and expertise.',
  help_card_2_button_text: 'Join Us',
  help_card_2_link: '/contact-us',
  help_card_3_title: 'Start a Fundraiser',
  help_card_3_description: 'Create your own campaign and rally your friends and family for a cause you love.',
  help_card_3_button_text: 'Start Now',
  help_card_3_link: '/#campaigns',
  cta_title: 'Ready to Make a Difference?',
  cta_subtitle: 'Join thousands of donors who are already changing lives. Start your giving journey today.',
  cta_primary_cta_text: 'Donate Now',
  cta_primary_cta_link: '/donation',
  cta_secondary_cta_text: 'Browse Causes',
  cta_secondary_cta_link: '/#campaigns',
  team_badge: 'Our Team',
  team_title: 'Meet the Changemakers',
  team_subtitle: 'Dedicated professionals working tirelessly behind the scenes to maximize impact.',
  community_badge: 'Our Community',
  community_title: 'Together We Can Change the World',
  community_subtitle: 'Our global community of donors, volunteers, and campaign creators unites around a shared mission: making the world a better place, one act of generosity at a time.',
  community_primary_cta_text: 'Join the Community',
  community_primary_cta_link: '/register',
  community_secondary_cta_text: 'Learn More',
  community_secondary_cta_link: '/about-us',
  community_stat_1_value: '50K+',
  community_stat_1_label: 'Community Members',
  community_stat_2_value: '120+',
  community_stat_2_label: 'Countries Reached',
  community_stat_3_value: '98%',
  community_stat_3_label: 'Donor Satisfaction',
  community_stat_4_value: '$5M+',
  community_stat_4_label: 'Total Impact',
  partners_heading: 'Trusted By Global Partners',
  partner_logo_1: '',
  partner_logo_2: '',
  partner_logo_3: '',
  partner_logo_4: '',
  partner_logo_5: '',
  testimonial_title_prefix: 'Words From Our',
  testimonial_title_highlight: 'Donors',
  testimonial_description: 'Hear from the people who are making a real impact through our platform.',
  testimonial_quote: 'I was looking for a way to give back to education initiatives, and IRWA made the process incredibly transparent. Being able to see exactly where my money went and receiving updates from the campaign leaders is truly rewarding.',
  testimonial_name: 'Emily Thompson',
  testimonial_role: 'Monthly Donor',
  testimonial_avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=150&auto=format&fit=crop',
  about_page_heading: 'About IRWA',
  about_page_paragraph_1: 'IRWA combines beneficial Islamic knowledge, trusted guidance, and community support in one platform.',
  about_page_paragraph_2: 'We publish articles and fatwas to serve the dawah mission, while also supporting meaningful causes that help people on the ground.',
  about_page_paragraph_3: 'Explore our latest articles, browse fatwas, or support an active cause through the resources below.',
  faq_1_question: 'How do donations work on IRWA?',
  faq_1_answer: 'Donations are processed securely through Stripe. Completed payments are verified after checkout and recorded for your dashboard.',
  faq_2_question: 'Can I read articles and fatwas without an account?',
  faq_2_answer: 'Yes. Public articles and fatwas are available without signing in. An account is only needed for donation and dashboard features.',
  faq_3_question: 'How can I contact the IRWA team?',
  faq_3_answer: 'Use the contact page for direct contact details and email information.',
  contact_page_heading: 'Get in Touch',
  contact_page_description: 'For general questions about articles, fatwas, campaigns, or technical help with donations, contact the IRWA team below.',
  request_fatwa_heading: 'Ask a Question',
  request_fatwa_description: 'Submit your question and the team can review it for a future published ruling.',
  request_fatwa_success_message: 'Your question has been submitted successfully.',
  newsletter_title: 'Stay Updated',
  newsletter_description: 'Get notified when new Islamic insights and fatwas are published.',
  newsletter_success_message: 'You are subscribed for new articles and fatwas.',
  nav_home_label: 'Home',
  nav_about_label: 'About Us',
  nav_articles_label: 'Articles',
  nav_fatwas_label: 'Fatwas',
  nav_search_label: 'Search',
  nav_causes_label: 'Causes',
  nav_pages_label: 'Pages',
  nav_causes_overview_label: 'Our Causes',
  nav_support_mission_label: 'Support the Mission',
  nav_faq_label: 'FAQ',
  nav_donate_label: 'Donate Us',
  nav_contact_label: 'Contact Us',
  nav_request_fatwa_label: 'Request Fatwa',
  nav_dashboard_label: 'My Dashboard',
  nav_admin_label: 'Admin Panel',
  nav_login_label: 'Login',
  nav_register_label: 'Register',
  top_bar_about_label: 'About',
  top_bar_faq_label: 'FAQ',
  top_bar_contact_label: 'Contact',
  footer_quick_links_heading: 'Quick Links',
  footer_causes_heading: 'Causes',
  footer_contact_heading: 'Contact',
  footer_home_label: 'Home',
  footer_about_label: 'About Us',
  footer_causes_label: 'Our Causes',
  footer_donate_label: 'Donate',
  footer_request_fatwa_label: 'Request Fatwa',
  footer_contact_label: 'Contact',
  cause_slider_badge: 'Featured Causes',
  cause_slider_title: 'Causes That Need Your Help',
  cause_slider_description: 'Every campaign is making a real difference. Be a part of it.',
  cause_slider_cta_text: 'View All Causes',
};

const textField = (name, label, description = '', type = 'text') => ({ name, label, description, type });
const textareaField = (name, label, description = '', rows = 3) => ({ name, label, description, type: 'textarea', rows });

export const SITE_SETTINGS_SECTIONS = [
  {
    id: 'branding',
    title: 'Branding & Contact',
    fields: [
      textField('site_name', 'Site Name'),
      textField('site_logo_url', 'Logo Image URL', 'Optional public logo URL.', 'url'),
      textField('contact_email', 'Contact Email', '', 'email'),
      textField('contact_phone', 'Contact Phone'),
      textField('contact_address', 'Contact Address'),
      textareaField('footer_description', 'Footer Description'),
      textField('social_facebook', 'Facebook URL', '', 'url'),
      textField('social_twitter', 'Twitter / X URL', '', 'url'),
      textField('social_instagram', 'Instagram URL', '', 'url'),
      textField('social_linkedin', 'LinkedIn URL', '', 'url'),
    ],
  },
  {
    id: 'hero',
    title: 'Homepage Hero',
    fields: [
      textField('hero_bg_image', 'Hero Background Image URL', '', 'url'),
      textField('hero_subtitle', 'Hero Badge Text'),
      textField('hero_title', 'Hero Title'),
      textareaField('hero_description', 'Hero Description'),
      textField('hero_primary_cta_text', 'Primary Button Text'),
      textField('hero_primary_cta_link', 'Primary Button Link'),
      textField('hero_secondary_cta_text', 'Secondary Button Text'),
      textField('hero_secondary_cta_link', 'Secondary Button Link'),
      textField('hero_support_cta_text', 'Support Link Text'),
      textField('hero_support_cta_link', 'Support Link URL'),
      ...repeat(3, (index) => [
        textField(`hero_stat_${index}_value`, `Hero Stat ${index} Value`),
        textField(`hero_stat_${index}_label`, `Hero Stat ${index} Label`),
      ]),
      ...repeat(4, (index) => [
        textField(`hero_card_${index}_title`, `Hero Card ${index} Title`),
        textField(`hero_card_${index}_meta`, `Hero Card ${index} Description`),
      ]),
    ],
  },
  {
    id: 'campaigns',
    title: 'Campaign Sections',
    fields: [
      textField('campaign_section_badge', 'Campaign Section Badge'),
      textField('campaign_section_title', 'Campaign Section Title'),
      textareaField('campaign_section_description', 'Campaign Section Description'),
      textField('campaign_section_empty_title', 'Campaign Empty State Title'),
      textareaField('campaign_section_empty_description', 'Campaign Empty State Description'),
      textField('campaign_discovery_badge', 'Discovery Section Badge'),
      textField('campaign_discovery_title', 'Discovery Section Title'),
      textareaField('campaign_discovery_description', 'Discovery Section Description'),
      textField('cause_bg_image', 'Campaign Section Background URL', '', 'url'),
      textField('cause_slider_badge', 'Featured Causes Badge'),
      textField('cause_slider_title', 'Featured Causes Title'),
      textareaField('cause_slider_description', 'Featured Causes Description'),
      textField('cause_slider_cta_text', 'Featured Causes CTA Text'),
    ],
  },
  {
    id: 'fatwas-blogs',
    title: 'Fatwa & Article Highlights',
    fields: [
      textField('fatwa_highlights_badge', 'Fatwa Highlights Badge'),
      textField('fatwa_highlights_title', 'Fatwa Highlights Title'),
      textareaField('fatwa_highlights_description', 'Fatwa Highlights Description'),
      textField('fatwa_highlights_cta_text', 'Fatwa Highlights CTA Text'),
      textField('blog_badge_text', 'Blog Section Badge'),
      textField('blog_title', 'Blog Section Title'),
      textareaField('blog_subtitle', 'Blog Section Description'),
      textField('blog_tag_1', 'Blog Tag 1'),
      textField('blog_tag_2', 'Blog Tag 2'),
      textField('blog_tag_3', 'Blog Tag 3'),
      textField('blog_tag_4', 'Blog Tag 4'),
      textField('blog_browse_cta_text', 'Browse Articles Button Text'),
    ],
  },
  {
    id: 'impact-journey-help',
    title: 'Impact, Journey & Help',
    fields: [
      textField('impact_badge', 'Impact Section Badge'),
      textField('impact_title', 'Impact Section Title'),
      textareaField('impact_description', 'Impact Section Description'),
      textField('impact_image_url', 'Impact Image URL', '', 'url'),
      textField('impact_image_alt', 'Impact Image Alt Text'),
      textField('impact_stat_value', 'Impact Stat Value'),
      textField('impact_stat_label', 'Impact Stat Label'),
      textField('impact_point_1', 'Impact Bullet 1'),
      textField('impact_point_2', 'Impact Bullet 2'),
      textField('impact_point_3', 'Impact Bullet 3'),
      textField('impact_cta_text', 'Impact CTA Text'),
      textField('impact_cta_link', 'Impact CTA Link'),
      textField('journey_badge', 'Journey Section Badge'),
      textField('journey_title', 'Journey Section Title'),
      textareaField('journey_description', 'Journey Section Description'),
      ...repeat(3, (index) => [
        textField(`journey_step_${index}_title`, `Journey Step ${index} Title`),
        textareaField(`journey_step_${index}_description`, `Journey Step ${index} Description`, '', 2),
      ]),
      textField('help_badge', 'Help Section Badge'),
      textField('help_title', 'Help Section Title'),
      textareaField('help_description', 'Help Section Description'),
      ...repeat(3, (index) => [
        textField(`help_card_${index}_title`, `Help Card ${index} Title`),
        textareaField(`help_card_${index}_description`, `Help Card ${index} Description`, '', 2),
        textField(`help_card_${index}_button_text`, `Help Card ${index} Button Text`),
        textField(`help_card_${index}_link`, `Help Card ${index} Link`),
      ]),
    ],
  },
  {
    id: 'cta-team-community',
    title: 'CTA, Team & Community',
    fields: [
      textField('cta_title', 'CTA Title'),
      textareaField('cta_subtitle', 'CTA Description'),
      textField('cta_primary_cta_text', 'CTA Primary Button Text'),
      textField('cta_primary_cta_link', 'CTA Primary Button Link'),
      textField('cta_secondary_cta_text', 'CTA Secondary Button Text'),
      textField('cta_secondary_cta_link', 'CTA Secondary Button Link'),
      textField('team_badge', 'Team Section Badge'),
      textField('team_title', 'Team Section Title'),
      textareaField('team_subtitle', 'Team Section Description'),
      textField('community_bg_image', 'Community Background URL', '', 'url'),
      textField('community_badge', 'Community Section Badge'),
      textField('community_title', 'Community Section Title'),
      textareaField('community_subtitle', 'Community Section Description'),
      textField('community_primary_cta_text', 'Community Primary Button Text'),
      textField('community_primary_cta_link', 'Community Primary Button Link'),
      textField('community_secondary_cta_text', 'Community Secondary Button Text'),
      textField('community_secondary_cta_link', 'Community Secondary Button Link'),
      ...repeat(4, (index) => [
        textField(`community_stat_${index}_value`, `Community Stat ${index} Value`),
        textField(`community_stat_${index}_label`, `Community Stat ${index} Label`),
      ]),
    ],
  },
  {
    id: 'partners-testimonial',
    title: 'Partners & Testimonial',
    fields: [
      textField('partners_heading', 'Partners Heading'),
      textField('partner_logo_1', 'Partner Logo / Text 1'),
      textField('partner_logo_2', 'Partner Logo / Text 2'),
      textField('partner_logo_3', 'Partner Logo / Text 3'),
      textField('partner_logo_4', 'Partner Logo / Text 4'),
      textField('partner_logo_5', 'Partner Logo / Text 5'),
      textField('testimonial_title_prefix', 'Testimonial Title Prefix'),
      textField('testimonial_title_highlight', 'Testimonial Highlight Word'),
      textareaField('testimonial_description', 'Testimonial Description'),
      textareaField('testimonial_quote', 'Testimonial Quote', '', 5),
      textField('testimonial_name', 'Testimonial Author Name'),
      textField('testimonial_role', 'Testimonial Author Role'),
      textField('testimonial_avatar_url', 'Testimonial Avatar URL', '', 'url'),
    ],
  },
  {
    id: 'static-pages',
    title: 'Static Pages & Newsletter',
    fields: [
      textField('nav_home_label', 'Header Home Label'),
      textField('nav_about_label', 'Header About Label'),
      textField('nav_articles_label', 'Header Articles Label'),
      textField('nav_fatwas_label', 'Header Fatwas Label'),
      textField('nav_search_label', 'Header Search Label'),
      textField('nav_causes_label', 'Header Causes Label'),
      textField('nav_pages_label', 'Header Pages Label'),
      textField('nav_causes_overview_label', 'Header Causes Overview Label'),
      textField('nav_support_mission_label', 'Header Support Mission Label'),
      textField('nav_faq_label', 'Header FAQ Label'),
      textField('nav_donate_label', 'Header Donate Label'),
      textField('nav_contact_label', 'Header Contact Label'),
      textField('nav_request_fatwa_label', 'Header Request Fatwa Label'),
      textField('nav_dashboard_label', 'Header Dashboard Label'),
      textField('nav_admin_label', 'Header Admin Label'),
      textField('nav_login_label', 'Header Login Label'),
      textField('nav_register_label', 'Header Register Label'),
      textField('top_bar_about_label', 'Top Bar About Label'),
      textField('top_bar_faq_label', 'Top Bar FAQ Label'),
      textField('top_bar_contact_label', 'Top Bar Contact Label'),
      textField('footer_quick_links_heading', 'Footer Quick Links Heading'),
      textField('footer_causes_heading', 'Footer Causes Heading'),
      textField('footer_contact_heading', 'Footer Contact Heading'),
      textField('footer_home_label', 'Footer Home Label'),
      textField('footer_about_label', 'Footer About Label'),
      textField('footer_causes_label', 'Footer Causes Link Label'),
      textField('footer_donate_label', 'Footer Donate Label'),
      textField('footer_request_fatwa_label', 'Footer Request Fatwa Label'),
      textField('footer_contact_label', 'Footer Contact Label'),
      textField('about_page_heading', 'About Page Heading'),
      textareaField('about_page_paragraph_1', 'About Paragraph 1'),
      textareaField('about_page_paragraph_2', 'About Paragraph 2'),
      textareaField('about_page_paragraph_3', 'About Paragraph 3'),
      ...repeat(3, (index) => [
        textField(`faq_${index}_question`, `FAQ ${index} Question`),
        textareaField(`faq_${index}_answer`, `FAQ ${index} Answer`, '', 3),
      ]),
      textField('contact_page_heading', 'Contact Page Heading'),
      textareaField('contact_page_description', 'Contact Page Description'),
      textField('request_fatwa_heading', 'Request Fatwa Heading'),
      textareaField('request_fatwa_description', 'Request Fatwa Description'),
      textareaField('request_fatwa_success_message', 'Request Fatwa Success Message', '', 2),
      textField('newsletter_title', 'Newsletter Title'),
      textareaField('newsletter_description', 'Newsletter Description', '', 2),
      textareaField('newsletter_success_message', 'Newsletter Success Message', '', 2),
    ],
  },
];

export function parseSiteSettingValue(value) {
  if (value == null) return '';

  try {
    return JSON.parse(value);
  } catch (error) {
    return String(value).replace(/^"|"$/g, '');
  }
}

export function mergeSiteSettings(rows = []) {
  const next = { ...DEFAULT_SITE_SETTINGS };

  for (const row of rows) {
    if (!row?.setting_key) continue;
    next[row.setting_key] = parseSiteSettingValue(row.setting_value);
  }

  return next;
}

export const GLOBAL_SETTINGS_SECTION_IDS = ['branding'];
export const SITE_BUILDER_SECTION_IDS = SITE_SETTINGS_SECTIONS.map((section) => section.id).filter(
  (sectionId) => !GLOBAL_SETTINGS_SECTION_IDS.includes(sectionId)
);
