-- IRWA content platform upgrade
-- Run in Supabase SQL editor before using the advanced content features.

alter table if exists public.blogs
  add column if not exists category text,
  add column if not exists tags text[] default '{}'::text[],
  add column if not exists featured boolean default false,
  add column if not exists slug text,
  add column if not exists author_name text,
  add column if not exists author_role text,
  add column if not exists author_bio text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists social_image text,
  add column if not exists view_count integer default 0;

alter table if exists public.fatwas
  add column if not exists question text,
  add column if not exists answer text,
  add column if not exists category text,
  add column if not exists tags text[] default '{}'::text[],
  add column if not exists featured boolean default false,
  add column if not exists slug text,
  add column if not exists author_name text,
  add column if not exists author_role text,
  add column if not exists author_bio text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists social_image text,
  add column if not exists view_count integer default 0;

create unique index if not exists blogs_slug_key on public.blogs (slug) where slug is not null;
create unique index if not exists fatwas_slug_key on public.fatwas (slug) where slug is not null;

create table if not exists public.newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'active',
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.fatwa_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  category text,
  question text not null,
  details text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);
