-- IRWA content platform upgrade
-- Run in Supabase SQL editor before using the advanced content features.

alter table if exists public.blogs
  add column if not exists category text,
  add column if not exists tags text[] default '{}'::text[],
  add column if not exists featured boolean default false,
  add column if not exists slug text,
  add column if not exists author_name text,
  add column if not exists author_role text,
  add column if not exists author_bio text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists social_image text,
  add column if not exists view_count integer default 0;

alter table if exists public.fatwas
  add column if not exists question text,
  add column if not exists answer text,
  add column if not exists category text,
  add column if not exists tags text[] default '{}'::text[],
  add column if not exists featured boolean default false,
  add column if not exists slug text,
  add column if not exists author_name text,
  add column if not exists author_role text,
  add column if not exists author_bio text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists social_image text,
  add column if not exists view_count integer default 0;

create unique index if not exists blogs_slug_key on public.blogs (slug) where slug is not null;
create unique index if not exists fatwas_slug_key on public.fatwas (slug) where slug is not null;

create table if not exists public.newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'active',
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.fatwa_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  category text,
  question text not null,
  details text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.location_consents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  permission_status text not null default 'granted',
  permission_state_before_request text,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_meters double precision,
  altitude_meters double precision,
  altitude_accuracy_meters double precision,
  heading_degrees double precision,
  speed_mps double precision,
  page_url text,
  page_path text,
  referrer text,
  time_zone text,
  language text,
  languages text[] not null default '{}'::text[],
  platform text,
  user_agent text,
  cookie_enabled boolean,
  do_not_track text,
  screen_width integer,
  screen_height integer,
  viewport_width integer,
  viewport_height integer,
  device_memory_gb double precision,
  hardware_concurrency integer,
  max_touch_points integer,
  online boolean,
  auth_user_id uuid,
  app_user_id integer references public.users(id) on delete set null,
  email text
);

create index if not exists idx_location_consents_created_at
  on public.location_consents (created_at desc);

create index if not exists idx_location_consents_auth_user_id
  on public.location_consents (auth_user_id);

create index if not exists idx_location_consents_app_user_id
  on public.location_consents (app_user_id);
