-- IRWA Dawah Platform foundation
-- Phase 1 database additions for scholar permissions, article taxonomy, and Quran progress.
-- Run in the Supabase SQL editor.

begin;

create or replace function public.current_user_email()
returns text
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select u.role
      from public.users u
      where lower(u.email) = public.current_user_email()
      limit 1
    ),
    'anonymous'
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select public.current_app_role() = 'admin';
$$;

create or replace function public.is_scholar()
returns boolean
language sql
stable
as $$
  select public.current_app_role() = 'scholar';
$$;

create or replace function public.is_admin_or_scholar()
returns boolean
language sql
stable
as $$
  select public.current_app_role() in ('admin', 'scholar');
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  existing_constraint text;
begin
  select con.conname
  into existing_constraint
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
  where nsp.nspname = 'public'
    and rel.relname = 'users'
    and con.contype = 'c'
    and pg_get_constraintdef(con.oid) ilike '%role%admin%donor%';

  if existing_constraint is not null then
    execute format('alter table public.users drop constraint %I', existing_constraint);
  end if;
end $$;

alter table if exists public.users
  add constraint users_role_check
  check (role in ('admin', 'donor', 'scholar'));

create table if not exists public.scholar_profiles (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name text not null,
  bio text,
  avatar_url text,
  credentials text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.article_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.user_quran_progress (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  surah_id smallint not null check (surah_id between 1 and 114),
  ayah_number integer not null check (ayah_number >= 1),
  last_read_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create index if not exists idx_scholar_profiles_user_id
  on public.scholar_profiles(user_id);

create index if not exists idx_article_categories_slug
  on public.article_categories(slug);

create index if not exists idx_user_quran_progress_user_id
  on public.user_quran_progress(user_id);

create index if not exists idx_user_quran_progress_surah_id
  on public.user_quran_progress(surah_id);

drop trigger if exists trg_scholar_profiles_updated_at on public.scholar_profiles;
create trigger trg_scholar_profiles_updated_at
before update on public.scholar_profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_user_quran_progress_updated_at on public.user_quran_progress;
create trigger trg_user_quran_progress_updated_at
before update on public.user_quran_progress
for each row
execute function public.set_updated_at();

insert into public.article_categories (name, slug)
values
  ('Aqeeda', 'aqeeda'),
  ('Fiqh', 'fiqh'),
  ('Seerah', 'seerah'),
  ('Tazkiyah', 'tazkiyah'),
  ('History', 'history'),
  ('Quran', 'quran'),
  ('Hadith', 'hadith'),
  ('Dawah', 'dawah')
on conflict (slug) do update
set name = excluded.name;

alter table public.scholar_profiles enable row level security;
alter table public.article_categories enable row level security;
alter table public.user_quran_progress enable row level security;
alter table public.blogs enable row level security;
alter table public.fatwas enable row level security;
alter table public.fatwa_requests enable row level security;
alter table public.donations enable row level security;

drop policy if exists "scholar_profiles_select_own_or_admin" on public.scholar_profiles;
create policy "scholar_profiles_select_own_or_admin"
on public.scholar_profiles
for select
using (
  public.is_admin()
  or user_id in (
    select id from public.users where lower(email) = public.current_user_email()
  )
);

drop policy if exists "scholar_profiles_insert_own_or_admin" on public.scholar_profiles;
create policy "scholar_profiles_insert_own_or_admin"
on public.scholar_profiles
for insert
with check (
  public.is_admin()
  or (
    public.is_scholar()
    and user_id in (
      select id from public.users where lower(email) = public.current_user_email()
    )
  )
);

drop policy if exists "scholar_profiles_update_own_or_admin" on public.scholar_profiles;
create policy "scholar_profiles_update_own_or_admin"
on public.scholar_profiles
for update
using (
  public.is_admin()
  or (
    public.is_scholar()
    and user_id in (
      select id from public.users where lower(email) = public.current_user_email()
    )
  )
)
with check (
  public.is_admin()
  or (
    public.is_scholar()
    and user_id in (
      select id from public.users where lower(email) = public.current_user_email()
    )
  )
);

drop policy if exists "article_categories_public_read" on public.article_categories;
create policy "article_categories_public_read"
on public.article_categories
for select
using (true);

drop policy if exists "article_categories_admin_manage" on public.article_categories;
create policy "article_categories_admin_manage"
on public.article_categories
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "user_quran_progress_select_own_or_admin" on public.user_quran_progress;
create policy "user_quran_progress_select_own_or_admin"
on public.user_quran_progress
for select
using (
  public.is_admin()
  or user_id in (
    select id from public.users where lower(email) = public.current_user_email()
  )
);

drop policy if exists "user_quran_progress_insert_own_or_admin" on public.user_quran_progress;
create policy "user_quran_progress_insert_own_or_admin"
on public.user_quran_progress
for insert
with check (
  public.is_admin()
  or user_id in (
    select id from public.users where lower(email) = public.current_user_email()
  )
);

drop policy if exists "user_quran_progress_update_own_or_admin" on public.user_quran_progress;
create policy "user_quran_progress_update_own_or_admin"
on public.user_quran_progress
for update
using (
  public.is_admin()
  or user_id in (
    select id from public.users where lower(email) = public.current_user_email()
  )
)
with check (
  public.is_admin()
  or user_id in (
    select id from public.users where lower(email) = public.current_user_email()
  )
);

drop policy if exists "user_quran_progress_delete_own_or_admin" on public.user_quran_progress;
create policy "user_quran_progress_delete_own_or_admin"
on public.user_quran_progress
for delete
using (
  public.is_admin()
  or user_id in (
    select id from public.users where lower(email) = public.current_user_email()
  )
);

drop policy if exists "blogs_public_read_published" on public.blogs;
create policy "blogs_public_read_published"
on public.blogs
for select
using (coalesce(status, 'draft') = 'published' or public.is_admin_or_scholar());

drop policy if exists "blogs_admin_manage" on public.blogs;
create policy "blogs_admin_manage"
on public.blogs
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "blogs_scholar_manage" on public.blogs;
create policy "blogs_scholar_manage"
on public.blogs
for all
using (public.is_scholar())
with check (public.is_scholar());

drop policy if exists "fatwas_public_read_published" on public.fatwas;
create policy "fatwas_public_read_published"
on public.fatwas
for select
using (coalesce(status, 'draft') = 'published' or public.is_admin_or_scholar());

drop policy if exists "fatwas_admin_manage" on public.fatwas;
create policy "fatwas_admin_manage"
on public.fatwas
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "fatwas_scholar_manage" on public.fatwas;
create policy "fatwas_scholar_manage"
on public.fatwas
for all
using (public.is_scholar())
with check (public.is_scholar());

drop policy if exists "fatwa_requests_admin_manage" on public.fatwa_requests;
create policy "fatwa_requests_admin_manage"
on public.fatwa_requests
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "fatwa_requests_scholar_manage" on public.fatwa_requests;
create policy "fatwa_requests_scholar_manage"
on public.fatwa_requests
for select
using (public.is_scholar());

drop policy if exists "fatwa_requests_scholar_update" on public.fatwa_requests;
create policy "fatwa_requests_scholar_update"
on public.fatwa_requests
for update
using (public.is_scholar())
with check (public.is_scholar());

drop policy if exists "donations_admin_full_access" on public.donations;
create policy "donations_admin_full_access"
on public.donations
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "donations_users_read_own" on public.donations;
create policy "donations_users_read_own"
on public.donations
for select
using (lower(coalesce(donor_email, '')) = public.current_user_email());

commit;
