-- IRWA learning courses foundation
-- Run in the Supabase SQL editor after the Dawah foundation migration.

begin;

create or replace function public.current_user_email()
returns text
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select u.role
      from public.users u
      where lower(u.email) = public.current_user_email()
      limit 1
    ),
    'anonymous'
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select public.current_app_role() = 'admin';
$$;

create or replace function public.is_scholar()
returns boolean
language sql
stable
as $$
  select public.current_app_role() = 'scholar';
$$;

create or replace function public.is_admin_or_scholar()
returns boolean
language sql
stable
as $$
  select public.current_app_role() in ('admin', 'scholar');
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  scholar_id bigint references public.scholar_profiles(id) on delete set null,
  cover_image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.course_modules (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  video_url text,
  order_index integer not null default 0,
  content_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_course_progress (
  user_id integer not null references public.users(id) on delete cascade,
  module_id bigint not null references public.course_modules(id) on delete cascade,
  is_completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, module_id)
);

create index if not exists idx_courses_scholar_id
  on public.courses(scholar_id);

create index if not exists idx_course_modules_course_id_order
  on public.course_modules(course_id, order_index);

create index if not exists idx_user_course_progress_user_id
  on public.user_course_progress(user_id);

create index if not exists idx_user_course_progress_module_id
  on public.user_course_progress(module_id);

drop trigger if exists trg_courses_updated_at on public.courses;
create trigger trg_courses_updated_at
before update on public.courses
for each row
execute function public.set_updated_at();

drop trigger if exists trg_course_modules_updated_at on public.course_modules;
create trigger trg_course_modules_updated_at
before update on public.course_modules
for each row
execute function public.set_updated_at();

drop trigger if exists trg_user_course_progress_updated_at on public.user_course_progress;
create trigger trg_user_course_progress_updated_at
before update on public.user_course_progress
for each row
execute function public.set_updated_at();

alter table public.courses enable row level security;
alter table public.course_modules enable row level security;
alter table public.user_course_progress enable row level security;

drop policy if exists "courses_public_read" on public.courses;
create policy "courses_public_read"
on public.courses
for select
using (true);

drop policy if exists "courses_admin_manage" on public.courses;
create policy "courses_admin_manage"
on public.courses
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "courses_scholar_manage" on public.courses;
create policy "courses_scholar_manage"
on public.courses
for all
using (public.is_scholar())
with check (public.is_scholar());

drop policy if exists "course_modules_public_read" on public.course_modules;
create policy "course_modules_public_read"
on public.course_modules
for select
using (true);

drop policy if exists "course_modules_admin_manage" on public.course_modules;
create policy "course_modules_admin_manage"
on public.course_modules
for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "course_modules_scholar_manage" on public.course_modules;
create policy "course_modules_scholar_manage"
on public.course_modules
for all
using (public.is_scholar())
with check (public.is_scholar());

drop policy if exists "user_course_progress_select_own_or_admin" on public.user_course_progress;
create policy "user_course_progress_select_own_or_admin"
on public.user_course_progress
for select
using (
  public.is_admin()
  or user_id in (
    select id
    from public.users
    where lower(email) = public.current_user_email()
  )
);

drop policy if exists "user_course_progress_insert_own_or_admin" on public.user_course_progress;
create policy "user_course_progress_insert_own_or_admin"
on public.user_course_progress
for insert
with check (
  public.is_admin()
  or user_id in (
    select id
    from public.users
    where lower(email) = public.current_user_email()
  )
);

drop policy if exists "user_course_progress_update_own_or_admin" on public.user_course_progress;
create policy "user_course_progress_update_own_or_admin"
on public.user_course_progress
for update
using (
  public.is_admin()
  or user_id in (
    select id
    from public.users
    where lower(email) = public.current_user_email()
  )
)
with check (
  public.is_admin()
  or user_id in (
    select id
    from public.users
    where lower(email) = public.current_user_email()
  )
);

drop policy if exists "user_course_progress_delete_own_or_admin" on public.user_course_progress;
create policy "user_course_progress_delete_own_or_admin"
on public.user_course_progress
for delete
using (
  public.is_admin()
  or user_id in (
    select id
    from public.users
    where lower(email) = public.current_user_email()
  )
);

commit;
