-- IRWAA Quran and Tafseer upgrade
-- Run this in the Supabase SQL editor before using /admin/quran.
-- Public visitors can read published Tafseer. Admins and scholars can draft/publish.

begin;

create or replace function public.current_user_email()
returns text
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''));
$$;

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select u.role
      from public.users u
      where lower(u.email) = public.current_user_email()
      limit 1
    ),
    'anonymous'
  );
$$;

create or replace function public.is_admin_or_scholar()
returns boolean
language sql
stable
as $$
  select public.current_app_role() in ('admin', 'scholar');
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.quran_surah_metadata (
  id bigint generated by default as identity primary key,
  surah_id smallint not null check (surah_id between 1 and 114),
  language text not null default 'en' check (language in ('en', 'bn', 'ar')),
  revelation_type text,
  intro text,
  objectives text,
  topics text,
  notes text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (surah_id, language)
);

create table if not exists public.quran_tafseer_sections (
  id bigint generated by default as identity primary key,
  surah_id smallint not null check (surah_id between 1 and 114),
  language text not null default 'en' check (language in ('en', 'bn', 'ar')),
  title text not null,
  slug text not null,
  ayah_start integer check (ayah_start is null or ayah_start >= 1),
  ayah_end integer check (ayah_end is null or ayah_end >= 1),
  order_index integer not null default 1,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (surah_id, language, slug),
  check (
    ayah_start is null
    or ayah_end is null
    or ayah_end >= ayah_start
  )
);

create table if not exists public.quran_tafseer_content (
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.quran_tafseer_sections(id) on delete cascade,
  language text not null default 'en' check (language in ('en', 'bn', 'ar')),
  title text not null,
  body text not null,
  references jsonb not null default '[]'::jsonb,
  author_name text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (section_id, language)
);

create index if not exists idx_quran_surah_metadata_lookup
  on public.quran_surah_metadata (surah_id, language, status);

create index if not exists idx_quran_tafseer_sections_lookup
  on public.quran_tafseer_sections (surah_id, language, status, order_index);

create index if not exists idx_quran_tafseer_content_lookup
  on public.quran_tafseer_content (section_id, language, status);

drop trigger if exists trg_quran_surah_metadata_updated_at on public.quran_surah_metadata;
create trigger trg_quran_surah_metadata_updated_at
before update on public.quran_surah_metadata
for each row execute function public.set_updated_at();

drop trigger if exists trg_quran_tafseer_sections_updated_at on public.quran_tafseer_sections;
create trigger trg_quran_tafseer_sections_updated_at
before update on public.quran_tafseer_sections
for each row execute function public.set_updated_at();

drop trigger if exists trg_quran_tafseer_content_updated_at on public.quran_tafseer_content;
create trigger trg_quran_tafseer_content_updated_at
before update on public.quran_tafseer_content
for each row execute function public.set_updated_at();

alter table public.quran_surah_metadata enable row level security;
alter table public.quran_tafseer_sections enable row level security;
alter table public.quran_tafseer_content enable row level security;

drop policy if exists "quran_surah_metadata_public_read_published" on public.quran_surah_metadata;
create policy "quran_surah_metadata_public_read_published"
on public.quran_surah_metadata
for select
using (status = 'published' or public.is_admin_or_scholar());

drop policy if exists "quran_surah_metadata_admin_scholar_manage" on public.quran_surah_metadata;
create policy "quran_surah_metadata_admin_scholar_manage"
on public.quran_surah_metadata
for all
using (public.is_admin_or_scholar())
with check (public.is_admin_or_scholar());

drop policy if exists "quran_tafseer_sections_public_read_published" on public.quran_tafseer_sections;
create policy "quran_tafseer_sections_public_read_published"
on public.quran_tafseer_sections
for select
using (status = 'published' or public.is_admin_or_scholar());

drop policy if exists "quran_tafseer_sections_admin_scholar_manage" on public.quran_tafseer_sections;
create policy "quran_tafseer_sections_admin_scholar_manage"
on public.quran_tafseer_sections
for all
using (public.is_admin_or_scholar())
with check (public.is_admin_or_scholar());

drop policy if exists "quran_tafseer_content_public_read_published" on public.quran_tafseer_content;
create policy "quran_tafseer_content_public_read_published"
on public.quran_tafseer_content
for select
using (status = 'published' or public.is_admin_or_scholar());

drop policy if exists "quran_tafseer_content_admin_scholar_manage" on public.quran_tafseer_content;
create policy "quran_tafseer_content_admin_scholar_manage"
on public.quran_tafseer_content
for all
using (public.is_admin_or_scholar())
with check (public.is_admin_or_scholar());

commit;
