export const SURAH_LIST = [
  {
    number: 1,
    name: "Al-Fatihah",
    arabicName: "الفاتحة",
    englishName: "The Opening",
    ayahs: 7,
    revelationType: "Makki",
  },
  {
    number: 2,
    name: "Al-Baqarah",
    arabicName: "البقرة",
    englishName: "The Cow",
    ayahs: 286,
    revelationType: "Madani",
  },
  {
    number: 3,
    name: "Ali 'Imran",
    arabicName: "آل عمران",
    englishName: "Family of Imran",
    ayahs: 200,
    revelationType: "Madani",
  },
  {
    number: 4,
    name: "An-Nisa",
    arabicName: "النساء",
    englishName: "The Women",
    ayahs: 176,
    revelationType: "Madani",
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    arabicName: "المائدة",
    englishName: "The Table Spread",
    ayahs: 120,
    revelationType: "Madani",
  },
  {
    number: 6,
    name: "Al-An'am",
    arabicName: "الأنعام",
    englishName: "The Cattle",
    ayahs: 165,
    revelationType: "Makki",
  },
  {
    number: 7,
    name: "Al-A'raf",
    arabicName: "الأعراف",
    englishName: "The Heights",
    ayahs: 206,
    revelationType: "Makki",
  },
  {
    number: 8,
    name: "Al-Anfal",
    arabicName: "الأنفال",
    englishName: "The Spoils of War",
    ayahs: 75,
    revelationType: "Madani",
  },
  {
    number: 9,
    name: "At-Tawbah",
    arabicName: "التوبة",
    englishName: "The Repentance",
    ayahs: 129,
    revelationType: "Madani",
  },
  {
    number: 10,
    name: "Yunus",
    arabicName: "يونس",
    englishName: "Jonah",
    ayahs: 109,
    revelationType: "Makki",
  },
  {
    number: 11,
    name: "Hud",
    arabicName: "هود",
    englishName: "Hud",
    ayahs: 123,
    revelationType: "Makki",
  },
  {
    number: 12,
    name: "Yusuf",
    arabicName: "يوسف",
    englishName: "Joseph",
    ayahs: 111,
    revelationType: "Makki",
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    arabicName: "الرعد",
    englishName: "The Thunder",
    ayahs: 43,
    revelationType: "Madani",
  },
  {
    number: 14,
    name: "Ibrahim",
    arabicName: "إبراهيم",
    englishName: "Abraham",
    ayahs: 52,
    revelationType: "Makki",
  },
  {
    number: 15,
    name: "Al-Hijr",
    arabicName: "الحجر",
    englishName: "The Rocky Tract",
    ayahs: 99,
    revelationType: "Makki",
  },
  {
    number: 16,
    name: "An-Nahl",
    arabicName: "النحل",
    englishName: "The Bee",
    ayahs: 128,
    revelationType: "Makki",
  },
  {
    number: 17,
    name: "Al-Isra",
    arabicName: "الإسراء",
    englishName: "The Night Journey",
    ayahs: 111,
    revelationType: "Makki",
  },
  {
    number: 18,
    name: "Al-Kahf",
    arabicName: "الكهف",
    englishName: "The Cave",
    ayahs: 110,
    revelationType: "Makki",
  },
  {
    number: 19,
    name: "Maryam",
    arabicName: "مريم",
    englishName: "Mary",
    ayahs: 98,
    revelationType: "Makki",
  },
  {
    number: 20,
    name: "Taha",
    arabicName: "طه",
    englishName: "Ta-Ha",
    ayahs: 135,
    revelationType: "Makki",
  },
  {
    number: 21,
    name: "Al-Anbiya",
    arabicName: "الأنبياء",
    englishName: "The Prophets",
    ayahs: 112,
    revelationType: "Makki",
  },
  {
    number: 22,
    name: "Al-Hajj",
    arabicName: "الحج",
    englishName: "The Pilgrimage",
    ayahs: 78,
    revelationType: "Madani",
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    arabicName: "المؤمنون",
    englishName: "The Believers",
    ayahs: 118,
    revelationType: "Makki",
  },
  {
    number: 24,
    name: "An-Nur",
    arabicName: "النور",
    englishName: "The Light",
    ayahs: 64,
    revelationType: "Madani",
  },
  {
    number: 25,
    name: "Al-Furqan",
    arabicName: "الفرقان",
    englishName: "The Criterion",
    ayahs: 77,
    revelationType: "Makki",
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    arabicName: "الشعراء",
    englishName: "The Poets",
    ayahs: 227,
    revelationType: "Makki",
  },
  {
    number: 27,
    name: "An-Naml",
    arabicName: "النمل",
    englishName: "The Ant",
    ayahs: 93,
    revelationType: "Makki",
  },
  {
    number: 28,
    name: "Al-Qasas",
    arabicName: "القصص",
    englishName: "The Stories",
    ayahs: 88,
    revelationType: "Makki",
  },
  {
    number: 29,
    name: "Al-'Ankabut",
    arabicName: "العنكبوت",
    englishName: "The Spider",
    ayahs: 69,
    revelationType: "Makki",
  },
  {
    number: 30,
    name: "Ar-Rum",
    arabicName: "الروم",
    englishName: "The Romans",
    ayahs: 60,
    revelationType: "Makki",
  },
  {
    number: 31,
    name: "Luqman",
    arabicName: "لقمان",
    englishName: "Luqman",
    ayahs: 34,
    revelationType: "Makki",
  },
  {
    number: 32,
    name: "As-Sajdah",
    arabicName: "السجدة",
    englishName: "The Prostration",
    ayahs: 30,
    revelationType: "Makki",
  },
  {
    number: 33,
    name: "Al-Ahzab",
    arabicName: "الأحزاب",
    englishName: "The Combined Forces",
    ayahs: 73,
    revelationType: "Madani",
  },
  {
    number: 34,
    name: "Saba",
    arabicName: "سبأ",
    englishName: "Sheba",
    ayahs: 54,
    revelationType: "Makki",
  },
  {
    number: 35,
    name: "Fatir",
    arabicName: "فاطر",
    englishName: "Originator",
    ayahs: 45,
    revelationType: "Makki",
  },
  {
    number: 36,
    name: "Ya-Sin",
    arabicName: "يس",
    englishName: "Ya-Sin",
    ayahs: 83,
    revelationType: "Makki",
  },
  {
    number: 37,
    name: "As-Saffat",
    arabicName: "الصافات",
    englishName: "Those Who Set The Ranks",
    ayahs: 182,
    revelationType: "Makki",
  },
  {
    number: 38,
    name: "Sad",
    arabicName: "ص",
    englishName: "Sad",
    ayahs: 88,
    revelationType: "Makki",
  },
  {
    number: 39,
    name: "Az-Zumar",
    arabicName: "الزمر",
    englishName: "The Groups",
    ayahs: 75,
    revelationType: "Makki",
  },
  {
    number: 40,
    name: "Ghafir",
    arabicName: "غافر",
    englishName: "The Forgiver",
    ayahs: 85,
    revelationType: "Makki",
  },
  {
    number: 41,
    name: "Fussilat",
    arabicName: "فصلت",
    englishName: "Explained in Detail",
    ayahs: 54,
    revelationType: "Makki",
  },
  {
    number: 42,
    name: "Ash-Shura",
    arabicName: "الشورى",
    englishName: "The Consultation",
    ayahs: 53,
    revelationType: "Makki",
  },
  {
    number: 43,
    name: "Az-Zukhruf",
    arabicName: "الزخرف",
    englishName: "The Ornaments of Gold",
    ayahs: 89,
    revelationType: "Makki",
  },
  {
    number: 44,
    name: "Ad-Dukhan",
    arabicName: "الدخان",
    englishName: "The Smoke",
    ayahs: 59,
    revelationType: "Makki",
  },
  {
    number: 45,
    name: "Al-Jathiyah",
    arabicName: "الجاثية",
    englishName: "The Crouching",
    ayahs: 37,
    revelationType: "Makki",
  },
  {
    number: 46,
    name: "Al-Ahqaf",
    arabicName: "الأحقاف",
    englishName: "The Wind-Curved Sandhills",
    ayahs: 35,
    revelationType: "Makki",
  },
  {
    number: 47,
    name: "Muhammad",
    arabicName: "محمد",
    englishName: "Muhammad",
    ayahs: 38,
    revelationType: "Madani",
  },
  {
    number: 48,
    name: "Al-Fath",
    arabicName: "الفتح",
    englishName: "The Victory",
    ayahs: 29,
    revelationType: "Madani",
  },
  {
    number: 49,
    name: "Al-Hujurat",
    arabicName: "الحجرات",
    englishName: "The Rooms",
    ayahs: 18,
    revelationType: "Madani",
  },
  {
    number: 50,
    name: "Qaf",
    arabicName: "ق",
    englishName: "Qaf",
    ayahs: 45,
    revelationType: "Makki",
  },
  {
    number: 51,
    name: "Adh-Dhariyat",
    arabicName: "الذاريات",
    englishName: "The Winnowing Winds",
    ayahs: 60,
    revelationType: "Makki",
  },
  {
    number: 52,
    name: "At-Tur",
    arabicName: "الطور",
    englishName: "The Mount",
    ayahs: 49,
    revelationType: "Makki",
  },
  {
    number: 53,
    name: "An-Najm",
    arabicName: "النجم",
    englishName: "The Star",
    ayahs: 62,
    revelationType: "Makki",
  },
  {
    number: 54,
    name: "Al-Qamar",
    arabicName: "القمر",
    englishName: "The Moon",
    ayahs: 55,
    revelationType: "Makki",
  },
  {
    number: 55,
    name: "Ar-Rahman",
    arabicName: "الرحمن",
    englishName: "The Beneficent",
    ayahs: 78,
    revelationType: "Madani",
  },
  {
    number: 56,
    name: "Al-Waqi'ah",
    arabicName: "الواقعة",
    englishName: "The Inevitable",
    ayahs: 96,
    revelationType: "Makki",
  },
  {
    number: 57,
    name: "Al-Hadid",
    arabicName: "الحديد",
    englishName: "The Iron",
    ayahs: 29,
    revelationType: "Madani",
  },
  {
    number: 58,
    name: "Al-Mujadilah",
    arabicName: "المجادلة",
    englishName: "The Pleading Woman",
    ayahs: 22,
    revelationType: "Madani",
  },
  {
    number: 59,
    name: "Al-Hashr",
    arabicName: "الحشر",
    englishName: "The Exile",
    ayahs: 24,
    revelationType: "Madani",
  },
  {
    number: 60,
    name: "Al-Mumtahanah",
    arabicName: "الممتحنة",
    englishName: "She That Is To Be Examined",
    ayahs: 13,
    revelationType: "Madani",
  },
  {
    number: 61,
    name: "As-Saf",
    arabicName: "الصف",
    englishName: "The Ranks",
    ayahs: 14,
    revelationType: "Madani",
  },
  {
    number: 62,
    name: "Al-Jumu'ah",
    arabicName: "الجمعة",
    englishName: "Friday",
    ayahs: 11,
    revelationType: "Madani",
  },
  {
    number: 63,
    name: "Al-Munafiqun",
    arabicName: "المنافقون",
    englishName: "The Hypocrites",
    ayahs: 11,
    revelationType: "Madani",
  },
  {
    number: 64,
    name: "At-Taghabun",
    arabicName: "التغابن",
    englishName: "The Mutual Disillusion",
    ayahs: 18,
    revelationType: "Madani",
  },
  {
    number: 65,
    name: "At-Talaq",
    arabicName: "الطلاق",
    englishName: "Divorce",
    ayahs: 12,
    revelationType: "Madani",
  },
  {
    number: 66,
    name: "At-Tahrim",
    arabicName: "التحريم",
    englishName: "The Prohibition",
    ayahs: 12,
    revelationType: "Madani",
  },
  {
    number: 67,
    name: "Al-Mulk",
    arabicName: "الملك",
    englishName: "The Sovereignty",
    ayahs: 30,
    revelationType: "Makki",
  },
  {
    number: 68,
    name: "Al-Qalam",
    arabicName: "القلم",
    englishName: "The Pen",
    ayahs: 52,
    revelationType: "Makki",
  },
  {
    number: 69,
    name: "Al-Haqqah",
    arabicName: "الحاقة",
    englishName: "The Reality",
    ayahs: 52,
    revelationType: "Makki",
  },
  {
    number: 70,
    name: "Al-Ma'arij",
    arabicName: "المعارج",
    englishName: "The Ascending Stairways",
    ayahs: 44,
    revelationType: "Makki",
  },
  {
    number: 71,
    name: "Nuh",
    arabicName: "نوح",
    englishName: "Noah",
    ayahs: 28,
    revelationType: "Makki",
  },
  {
    number: 72,
    name: "Al-Jinn",
    arabicName: "الجن",
    englishName: "The Jinn",
    ayahs: 28,
    revelationType: "Makki",
  },
  {
    number: 73,
    name: "Al-Muzzammil",
    arabicName: "المزمل",
    englishName: "The Enshrouded One",
    ayahs: 20,
    revelationType: "Makki",
  },
  {
    number: 74,
    name: "Al-Muddaththir",
    arabicName: "المدثر",
    englishName: "The Cloaked One",
    ayahs: 56,
    revelationType: "Makki",
  },
  {
    number: 75,
    name: "Al-Qiyamah",
    arabicName: "القيامة",
    englishName: "The Resurrection",
    ayahs: 40,
    revelationType: "Makki",
  },
  {
    number: 76,
    name: "Al-Insan",
    arabicName: "الإنسان",
    englishName: "Man",
    ayahs: 31,
    revelationType: "Madani",
  },
  {
    number: 77,
    name: "Al-Mursalat",
    arabicName: "المرسلات",
    englishName: "The Emissaries",
    ayahs: 50,
    revelationType: "Makki",
  },
  {
    number: 78,
    name: "An-Naba",
    arabicName: "النبأ",
    englishName: "The Tidings",
    ayahs: 40,
    revelationType: "Makki",
  },
  {
    number: 79,
    name: "An-Nazi'at",
    arabicName: "النازعات",
    englishName: "Those Who Drag Forth",
    ayahs: 46,
    revelationType: "Makki",
  },
  {
    number: 80,
    name: "'Abasa",
    arabicName: "عبس",
    englishName: "He Frowned",
    ayahs: 42,
    revelationType: "Makki",
  },
  {
    number: 81,
    name: "At-Takwir",
    arabicName: "التكوير",
    englishName: "The Overthrowing",
    ayahs: 29,
    revelationType: "Makki",
  },
  {
    number: 82,
    name: "Al-Infitar",
    arabicName: "الانفطار",
    englishName: "The Cleaving",
    ayahs: 19,
    revelationType: "Makki",
  },
  {
    number: 83,
    name: "Al-Mutaffifin",
    arabicName: "المطففين",
    englishName: "Defrauding",
    ayahs: 36,
    revelationType: "Makki",
  },
  {
    number: 84,
    name: "Al-Inshiqaq",
    arabicName: "الانشقاق",
    englishName: "The Sundering",
    ayahs: 25,
    revelationType: "Makki",
  },
  {
    number: 85,
    name: "Al-Buruj",
    arabicName: "البروج",
    englishName: "The Mansions of the Stars",
    ayahs: 22,
    revelationType: "Makki",
  },
  {
    number: 86,
    name: "At-Tariq",
    arabicName: "الطارق",
    englishName: "The Nightcomer",
    ayahs: 17,
    revelationType: "Makki",
  },
  {
    number: 87,
    name: "Al-A'la",
    arabicName: "الأعلى",
    englishName: "The Most High",
    ayahs: 19,
    revelationType: "Makki",
  },
  {
    number: 88,
    name: "Al-Ghashiyah",
    arabicName: "الغاشية",
    englishName: "The Overwhelming",
    ayahs: 26,
    revelationType: "Makki",
  },
  {
    number: 89,
    name: "Al-Fajr",
    arabicName: "الفجر",
    englishName: "The Dawn",
    ayahs: 30,
    revelationType: "Makki",
  },
  {
    number: 90,
    name: "Al-Balad",
    arabicName: "البلد",
    englishName: "The City",
    ayahs: 20,
    revelationType: "Makki",
  },
  {
    number: 91,
    name: "Ash-Shams",
    arabicName: "الشمس",
    englishName: "The Sun",
    ayahs: 15,
    revelationType: "Makki",
  },
  {
    number: 92,
    name: "Al-Layl",
    arabicName: "الليل",
    englishName: "The Night",
    ayahs: 21,
    revelationType: "Makki",
  },
  {
    number: 93,
    name: "Ad-Duha",
    arabicName: "الضحى",
    englishName: "The Morning Hours",
    ayahs: 11,
    revelationType: "Makki",
  },
  {
    number: 94,
    name: "Ash-Sharh",
    arabicName: "الشرح",
    englishName: "The Relief",
    ayahs: 8,
    revelationType: "Makki",
  },
  {
    number: 95,
    name: "At-Tin",
    arabicName: "التين",
    englishName: "The Fig",
    ayahs: 8,
    revelationType: "Makki",
  },
  {
    number: 96,
    name: "Al-'Alaq",
    arabicName: "العلق",
    englishName: "The Clot",
    ayahs: 19,
    revelationType: "Makki",
  },
  {
    number: 97,
    name: "Al-Qadr",
    arabicName: "القدر",
    englishName: "The Power",
    ayahs: 5,
    revelationType: "Makki",
  },
  {
    number: 98,
    name: "Al-Bayyinah",
    arabicName: "البينة",
    englishName: "The Clear Proof",
    ayahs: 8,
    revelationType: "Madani",
  },
  {
    number: 99,
    name: "Az-Zalzalah",
    arabicName: "الزلزلة",
    englishName: "The Earthquake",
    ayahs: 8,
    revelationType: "Madani",
  },
  {
    number: 100,
    name: "Al-'Adiyat",
    arabicName: "العاديات",
    englishName: "The Courser",
    ayahs: 11,
    revelationType: "Makki",
  },
  {
    number: 101,
    name: "Al-Qari'ah",
    arabicName: "القارعة",
    englishName: "The Calamity",
    ayahs: 11,
    revelationType: "Makki",
  },
  {
    number: 102,
    name: "At-Takathur",
    arabicName: "التكاثر",
    englishName: "Rivalry in World Increase",
    ayahs: 8,
    revelationType: "Makki",
  },
  {
    number: 103,
    name: "Al-'Asr",
    arabicName: "العصر",
    englishName: "The Declining Day",
    ayahs: 3,
    revelationType: "Makki",
  },
  {
    number: 104,
    name: "Al-Humazah",
    arabicName: "الهمزة",
    englishName: "The Traducer",
    ayahs: 9,
    revelationType: "Makki",
  },
  {
    number: 105,
    name: "Al-Fil",
    arabicName: "الفيل",
    englishName: "The Elephant",
    ayahs: 5,
    revelationType: "Makki",
  },
  {
    number: 106,
    name: "Quraysh",
    arabicName: "قريش",
    englishName: "Quraysh",
    ayahs: 4,
    revelationType: "Makki",
  },
  {
    number: 107,
    name: "Al-Ma'un",
    arabicName: "الماعون",
    englishName: "Small Kindnesses",
    ayahs: 7,
    revelationType: "Makki",
  },
  {
    number: 108,
    name: "Al-Kawthar",
    arabicName: "الكوثر",
    englishName: "Abundance",
    ayahs: 3,
    revelationType: "Makki",
  },
  {
    number: 109,
    name: "Al-Kafirun",
    arabicName: "الكافرون",
    englishName: "The Disbelievers",
    ayahs: 6,
    revelationType: "Makki",
  },
  {
    number: 110,
    name: "An-Nasr",
    arabicName: "النصر",
    englishName: "Divine Support",
    ayahs: 3,
    revelationType: "Madani",
  },
  {
    number: 111,
    name: "Al-Masad",
    arabicName: "المسد",
    englishName: "The Palm Fiber",
    ayahs: 5,
    revelationType: "Makki",
  },
  {
    number: 112,
    name: "Al-Ikhlas",
    arabicName: "الإخلاص",
    englishName: "Sincerity",
    ayahs: 4,
    revelationType: "Makki",
  },
  {
    number: 113,
    name: "Al-Falaq",
    arabicName: "الفلق",
    englishName: "The Daybreak",
    ayahs: 5,
    revelationType: "Makki",
  },
  {
    number: 114,
    name: "An-Nas",
    arabicName: "الناس",
    englishName: "Mankind",
    ayahs: 6,
    revelationType: "Makki",
  },
];

export const JUZ_SHORTCUTS = Array.from({ length: 30 }, (_, index) => ({
  number: index + 1,
  label: `Juz ${index + 1}`,
}));

export function getSurahById(surahId) {
  const id = Number(surahId);
  return SURAH_LIST.find((surah) => surah.number === id) || null;
}

export function getNextSurah(surahId) {
  return getSurahById(Number(surahId) + 1);
}

export function getPreviousSurah(surahId) {
  return getSurahById(Number(surahId) - 1);
}
